-- putting here customization of the Parser generated by Happy,
-- and which I didn't want to put in the Happy file.
module SimplyTyped.ParserWrapper where

import SimplyTyped.Lexer
import SimplyTyped.Parser

fullParser :: String -> Term
fullParser s =
  case lexer s of
    Left err -> error $ show err
    Right lexemes -> parseTerm lexemes
